-- Execute este arquivo uma única vez no SQL Editor do Supabase.
create table if not exists public.campanhas (
  id bigint generated by default as identity primary key,
  titulo text not null,
  mensagem text not null,
  imagem_url text not null,
  link_destino text,
  total_destinatarios integer not null default 0,
  enviados integer not null default 0,
  falhas integer not null default 0,
  status text not null default 'Rascunho',
  criado_em timestamptz not null default now()
);
create table if not exists public.campanha_envios (
  id bigint generated by default as identity primary key,
  campanha_id bigint references public.campanhas(id) on delete cascade,
  cliente_id bigint references public.clientes(id) on delete set null,
  telefone text not null,
  status text not null,
  whatsapp_message_id text,
  erro text,
  criado_em timestamptz not null default now()
);
alter table public.campanhas enable row level security;
alter table public.campanha_envios enable row level security;
drop policy if exists "Dono gerencia campanhas" on public.campanhas;
create policy "Dono gerencia campanhas" on public.campanhas for all using (public.usuario_e_dono()) with check (public.usuario_e_dono());
drop policy if exists "Dono gerencia envios" on public.campanha_envios;
create policy "Dono gerencia envios" on public.campanha_envios for all using (public.usuario_e_dono()) with check (public.usuario_e_dono());
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('promocoes','promocoes',true,5242880,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=true,file_size_limit=5242880,allowed_mime_types=array['image/jpeg','image/png','image/webp'];
drop policy if exists "Dono envia banners" on storage.objects;
create policy "Dono envia banners" on storage.objects for insert to authenticated with check (bucket_id='promocoes' and public.usuario_e_dono());
drop policy if exists "Banners públicos" on storage.objects;
create policy "Banners públicos" on storage.objects for select using (bucket_id='promocoes');
