-- PEDIDOFLOW 2.1 — CLIENTE SEM E-MAIL
-- Execute este arquivo no SQL Editor do Supabase.
-- O dono continua usando Supabase Auth.
-- O cliente usa celular + senha em uma tabela própria.

begin;

create extension if not exists pgcrypto;

-- Tabelas já existentes
create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text default '',
  preco numeric(10,2) not null check (preco >= 0),
  categoria text default 'Outros',
  imagem_url text default '',
  ativo boolean default true,
  criado_em timestamptz default now()
);

create table if not exists public.configuracoes (
  id bigint generated by default as identity primary key,
  nome_loja text not null default 'PedidoFlow Lanches',
  whatsapp text not null default '',
  taxa_entrega numeric(10,2) default 5 check (taxa_entrega >= 0),
  endereco text default 'Jequié - BA',
  chave_pix text default '',
  loja_aberta boolean default true,
  atualizado_em timestamptz default now()
);

create table if not exists public.perfis (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text default '',
  role text not null default 'cliente' check (role in ('cliente','dono')),
  whatsapp text default '',
  aceita_promocoes boolean not null default false,
  consentimento_em timestamptz,
  criado_em timestamptz default now()
);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  numero integer not null,
  cliente_id uuid references auth.users(id) on delete set null,
  cliente_nome text not null,
  cliente_telefone text default '',
  tipo_entrega text not null default 'Entrega',
  endereco text default '',
  bairro text default '',
  referencia text default '',
  pagamento text default '',
  observacoes text default '',
  subtotal numeric(10,2) not null default 0,
  taxa_entrega numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  status text not null default 'Recebido',
  itens jsonb not null default '[]'::jsonb,
  criado_em timestamptz default now()
);

-- Nova tabela de clientes, sem Supabase Auth
create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  nome text not null,
  whatsapp text not null unique,
  senha_hash text not null,
  endereco text not null default '',
  numero text not null default '',
  bairro text not null default '',
  cidade text not null default '',
  referencia text default '',
  aceita_promocoes boolean not null default false,
  consentimento_em timestamptz,
  sessao_token uuid,
  sessao_expira_em timestamptz,
  criado_em timestamptz default now(),
  atualizado_em timestamptz default now()
);

alter table public.pedidos
add column if not exists cliente_cadastro_id bigint
references public.clientes(id) on delete set null;

-- Função de dono
create or replace function public.usuario_e_dono()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.perfis
    where id = auth.uid() and role = 'dono'
  );
$$;

revoke all on function public.usuario_e_dono() from public;
grant execute on function public.usuario_e_dono() to authenticated;

-- Cadastro do cliente
create or replace function public.cadastrar_cliente(
  p_nome text,
  p_whatsapp text,
  p_senha text,
  p_endereco text,
  p_numero text,
  p_bairro text,
  p_cidade text,
  p_referencia text default '',
  p_aceita_promocoes boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_phone text;
  v_token uuid;
  v_cliente public.clientes;
begin
  v_phone := regexp_replace(coalesce(p_whatsapp,''), '\D', '', 'g');

  if length(trim(coalesce(p_nome,''))) < 3 then
    raise exception 'Informe um nome válido.';
  end if;
  if length(v_phone) not between 10 and 11 then
    raise exception 'Informe um celular válido com DDD.';
  end if;
  if length(coalesce(p_senha,'')) < 6 then
    raise exception 'A senha precisa ter pelo menos 6 caracteres.';
  end if;
  if length(trim(coalesce(p_endereco,''))) < 4 then
    raise exception 'Informe a rua ou avenida.';
  end if;
  if trim(coalesce(p_numero,'')) = '' then
    raise exception 'Informe o número do endereço.';
  end if;
  if length(trim(coalesce(p_bairro,''))) < 2 then
    raise exception 'Informe o bairro.';
  end if;

  if exists(select 1 from public.clientes where whatsapp = v_phone) then
    raise exception 'Este celular já possui cadastro.';
  end if;

  v_token := gen_random_uuid();

  insert into public.clientes (
    nome, whatsapp, senha_hash, endereco, numero, bairro, cidade,
    referencia, aceita_promocoes, consentimento_em,
    sessao_token, sessao_expira_em
  ) values (
    trim(p_nome), v_phone, crypt(p_senha, gen_salt('bf')),
    trim(p_endereco), trim(p_numero), trim(p_bairro), trim(p_cidade),
    trim(coalesce(p_referencia,'')), p_aceita_promocoes,
    case when p_aceita_promocoes then now() else null end,
    v_token, now() + interval '90 days'
  )
  returning * into v_cliente;

  return jsonb_build_object(
    'token', v_token,
    'cliente', jsonb_build_object(
      'id', v_cliente.id,
      'nome', v_cliente.nome,
      'whatsapp', v_cliente.whatsapp,
      'endereco', v_cliente.endereco,
      'numero', v_cliente.numero,
      'bairro', v_cliente.bairro,
      'cidade', v_cliente.cidade,
      'referencia', v_cliente.referencia,
      'aceita_promocoes', v_cliente.aceita_promocoes
    )
  );
end;
$$;

-- Login do cliente
create or replace function public.login_cliente(
  p_whatsapp text,
  p_senha text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_phone text;
  v_token uuid;
  v_cliente public.clientes;
begin
  v_phone := regexp_replace(coalesce(p_whatsapp,''), '\D', '', 'g');

  select * into v_cliente
  from public.clientes
  where whatsapp = v_phone;

  if v_cliente.id is null
     or v_cliente.senha_hash <> crypt(p_senha, v_cliente.senha_hash) then
    raise exception 'Celular ou senha inválidos.';
  end if;

  v_token := gen_random_uuid();

  update public.clientes
  set sessao_token = v_token,
      sessao_expira_em = now() + interval '90 days',
      atualizado_em = now()
  where id = v_cliente.id
  returning * into v_cliente;

  return jsonb_build_object(
    'token', v_token,
    'cliente', jsonb_build_object(
      'id', v_cliente.id,
      'nome', v_cliente.nome,
      'whatsapp', v_cliente.whatsapp,
      'endereco', v_cliente.endereco,
      'numero', v_cliente.numero,
      'bairro', v_cliente.bairro,
      'cidade', v_cliente.cidade,
      'referencia', v_cliente.referencia,
      'aceita_promocoes', v_cliente.aceita_promocoes
    )
  );
end;
$$;

-- Recupera cliente pela sessão
create or replace function public.obter_cliente_sessao(p_token uuid)
returns jsonb
language sql
security definer
set search_path = public
stable
as $$
  select jsonb_build_object(
    'id', id,
    'nome', nome,
    'whatsapp', whatsapp,
    'endereco', endereco,
    'numero', numero,
    'bairro', bairro,
    'cidade', cidade,
    'referencia', referencia,
    'aceita_promocoes', aceita_promocoes
  )
  from public.clientes
  where sessao_token = p_token
    and sessao_expira_em > now();
$$;

-- Salva pedido associado ao cliente
create or replace function public.registrar_pedido_cliente(
  p_token uuid,
  p_numero integer,
  p_cliente_nome text,
  p_cliente_telefone text,
  p_tipo_entrega text,
  p_endereco text,
  p_bairro text,
  p_referencia text,
  p_pagamento text,
  p_observacoes text,
  p_subtotal numeric,
  p_taxa_entrega numeric,
  p_total numeric,
  p_itens jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cliente_id bigint;
  v_pedido_id bigint;
begin
  select id into v_cliente_id
  from public.clientes
  where sessao_token = p_token
    and sessao_expira_em > now();

  if v_cliente_id is null then
    raise exception 'Sessão expirada. Entre novamente.';
  end if;

  insert into public.pedidos (
    numero, cliente_cadastro_id, cliente_nome, cliente_telefone,
    tipo_entrega, endereco, bairro, referencia, pagamento,
    observacoes, subtotal, taxa_entrega, total, status, itens
  ) values (
    p_numero, v_cliente_id, trim(p_cliente_nome),
    regexp_replace(coalesce(p_cliente_telefone,''), '\D', '', 'g'),
    p_tipo_entrega, coalesce(p_endereco,''), coalesce(p_bairro,''),
    coalesce(p_referencia,''), coalesce(p_pagamento,''),
    coalesce(p_observacoes,''), p_subtotal, p_taxa_entrega,
    p_total, 'Recebido', coalesce(p_itens,'[]'::jsonb)
  )
  returning id into v_pedido_id;

  return v_pedido_id;
end;
$$;

-- Histórico do cliente
create or replace function public.listar_pedidos_cliente(p_token uuid)
returns table (
  id bigint,
  numero integer,
  status text,
  total numeric,
  itens jsonb,
  criado_em timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select p.id, p.numero, p.status, p.total, p.itens, p.criado_em
  from public.pedidos p
  join public.clientes c on c.id = p.cliente_cadastro_id
  where c.sessao_token = p_token
    and c.sessao_expira_em > now()
  order by p.criado_em desc;
$$;

grant execute on function public.cadastrar_cliente(text,text,text,text,text,text,text,text,boolean) to anon, authenticated;
grant execute on function public.login_cliente(text,text) to anon, authenticated;
grant execute on function public.obter_cliente_sessao(uuid) to anon, authenticated;
grant execute on function public.registrar_pedido_cliente(uuid,integer,text,text,text,text,text,text,text,text,numeric,numeric,numeric,jsonb) to anon, authenticated;
grant execute on function public.listar_pedidos_cliente(uuid) to anon, authenticated;

-- RLS
alter table public.clientes enable row level security;
alter table public.produtos enable row level security;
alter table public.configuracoes enable row level security;
alter table public.perfis enable row level security;
alter table public.pedidos enable row level security;

drop policy if exists "Dono lê clientes internos" on public.clientes;
create policy "Dono lê clientes internos"
on public.clientes for select
to authenticated
using (public.usuario_e_dono());

drop policy if exists "Dono atualiza clientes internos" on public.clientes;
create policy "Dono atualiza clientes internos"
on public.clientes for update
to authenticated
using (public.usuario_e_dono())
with check (public.usuario_e_dono());

drop policy if exists "Dono lê todos os pedidos" on public.pedidos;
create policy "Dono lê todos os pedidos"
on public.pedidos for select
to authenticated
using (public.usuario_e_dono());

drop policy if exists "Dono atualiza pedidos" on public.pedidos;
create policy "Dono atualiza pedidos"
on public.pedidos for update
to authenticated
using (public.usuario_e_dono())
with check (public.usuario_e_dono());

-- Dados iniciais
insert into public.configuracoes
(nome_loja, whatsapp, taxa_entrega, endereco, chave_pix, loja_aberta)
select 'PedidoFlow Lanches', '5573999999999', 5.00, 'Jequié - BA', '', true
where not exists (select 1 from public.configuracoes);

commit;
