-- PEDIDOFLOW V2.1 — CONFIGURAÇÃO COMPLETA
-- Execute este arquivo uma vez no SQL Editor do Supabase.

-- 1. Tabelas principais
create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text default '',
  preco numeric(10,2) not null,
  categoria text default 'Outros',
  imagem_url text default '',
  ativo boolean default true,
  criado_em timestamptz default now()
);

create table if not exists public.configuracoes (
  id bigint generated by default as identity primary key,
  nome_loja text not null default 'PedidoFlow Lanches',
  whatsapp text not null default '',
  taxa_entrega numeric(10,2) default 5,
  endereco text default 'Jequié - BA',
  chave_pix text default '',
  loja_aberta boolean default true,
  atualizado_em timestamptz default now()
);

create table if not exists public.perfis (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text default '',
  role text not null default 'cliente' check (role in ('cliente','dono')),
  whatsapp text default '',
  aceita_promocoes boolean not null default false,
  consentimento_em timestamptz,
  criado_em timestamptz default now()
);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  numero integer not null,
  cliente_id uuid references auth.users(id) on delete set null,
  cliente_nome text not null,
  cliente_telefone text default '',
  tipo_entrega text default 'Entrega',
  endereco text default '',
  bairro text default '',
  referencia text default '',
  pagamento text default '',
  observacoes text default '',
  subtotal numeric(10,2) not null default 0,
  taxa_entrega numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  status text not null default 'Recebido',
  itens jsonb not null default '[]'::jsonb,
  criado_em timestamptz default now()
);

-- 2. Configuração inicial da loja, somente se estiver vazia
insert into public.configuracoes
(nome_loja, whatsapp, taxa_entrega, endereco, chave_pix, loja_aberta)
select
  'PedidoFlow Lanches',
  '5573999999999',
  5.00,
  'Jequié - BA',
  '',
  true
where not exists (select 1 from public.configuracoes);

-- 3. Produtos de demonstração, somente se a tabela estiver vazia
insert into public.produtos
(nome, descricao, preco, categoria, imagem_url, ativo)
select * from (
  values
  ('X-Burguer Clássico','Pão, carne artesanal, queijo, presunto, salada e molho especial.',18.90,'Hambúrgueres','https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80',true),
  ('X-Bacon Especial','Pão, carne artesanal, queijo, bacon crocante, salada e molho especial.',24.90,'Hambúrgueres','https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=80',true),
  ('X-Tudo da Casa','Carne, queijo, presunto, bacon, ovo, salada e molho da casa.',29.90,'Hambúrgueres','https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=900&q=80',true),
  ('Smash Cheddar','Dois smash burgers, cheddar cremoso, cebola caramelizada e molho.',27.90,'Hambúrgueres','https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=900&q=80',true),
  ('Pizza Calabresa','Molho de tomate, mussarela, calabresa, cebola e orégano.',42.00,'Pizzas','https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=80',true),
  ('Pizza Frango com Catupiry','Molho, mussarela, frango desfiado, catupiry e orégano.',46.00,'Pizzas','https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=80',true),
  ('Pizza Portuguesa','Mussarela, presunto, ovo, cebola, azeitona e orégano.',48.00,'Pizzas','https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=900&q=80',true),
  ('Pizza Quatro Queijos','Mussarela, parmesão, provolone e catupiry.',49.00,'Pizzas','https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&w=900&q=80',true),
  ('Coxinha de Frango','Coxinha crocante recheada com frango temperado.',7.00,'Salgados','https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?auto=format&fit=crop&w=900&q=80',true),
  ('Pastel de Carne','Pastel crocante recheado com carne moída temperada.',9.00,'Salgados','https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=900&q=80',true),
  ('Pastel de Queijo','Pastel crocante com queijo derretido.',9.00,'Salgados','https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80',true),
  ('Batata Frita','Porção de batata frita crocante com molho especial.',16.00,'Porções','https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=80',true),
  ('Batata com Cheddar e Bacon','Batata frita, cheddar cremoso e bacon crocante.',24.00,'Porções','https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?auto=format&fit=crop&w=900&q=80',true),
  ('Onion Rings','Anéis de cebola empanados e crocantes.',18.00,'Porções','https://images.unsplash.com/photo-1639024471283-03518883512d?auto=format&fit=crop&w=900&q=80',true),
  ('Refrigerante Lata','Refrigerante gelado, lata de 350 ml.',6.00,'Bebidas','https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&w=900&q=80',true),
  ('Refrigerante 1 Litro','Refrigerante gelado de 1 litro.',10.00,'Bebidas','https://images.unsplash.com/photo-1581636625402-29b2a704ef13?auto=format&fit=crop&w=900&q=80',true),
  ('Suco Natural','Suco natural preparado na hora.',8.00,'Bebidas','https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=900&q=80',true),
  ('Milk-shake Chocolate','Milk-shake cremoso de chocolate.',14.00,'Bebidas','https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=900&q=80',true),
  ('Brownie com Sorvete','Brownie de chocolate com sorvete de creme.',16.00,'Sobremesas','https://images.unsplash.com/photo-1564355808539-22fda35bed7e?auto=format&fit=crop&w=900&q=80',true),
  ('Pudim da Casa','Pudim cremoso com calda de caramelo.',9.00,'Sobremesas','https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&w=900&q=80',true)
) as demo(nome, descricao, preco, categoria, imagem_url, ativo)
where not exists (select 1 from public.produtos);

-- 4. Segurança
alter table public.produtos enable row level security;
alter table public.configuracoes enable row level security;
alter table public.perfis enable row level security;
alter table public.pedidos enable row level security;

drop policy if exists "Produtos visíveis publicamente" on public.produtos;
drop policy if exists "Dono cadastra produtos" on public.produtos;
drop policy if exists "Dono edita produtos" on public.produtos;
drop policy if exists "Dono exclui produtos" on public.produtos;

create policy "Produtos visíveis publicamente"
on public.produtos for select to anon,authenticated using (true);

create policy "Dono cadastra produtos"
on public.produtos for insert to authenticated
with check (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'));

create policy "Dono edita produtos"
on public.produtos for update to authenticated
using (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'))
with check (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'));

create policy "Dono exclui produtos"
on public.produtos for delete to authenticated
using (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'));

drop policy if exists "Configurações visíveis publicamente" on public.configuracoes;
drop policy if exists "Dono cadastra configurações" on public.configuracoes;
drop policy if exists "Dono edita configurações" on public.configuracoes;

create policy "Configurações visíveis publicamente"
on public.configuracoes for select to anon,authenticated using (true);

create policy "Dono cadastra configurações"
on public.configuracoes for insert to authenticated
with check (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'));

create policy "Dono edita configurações"
on public.configuracoes for update to authenticated
using (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'))
with check (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'));

drop policy if exists "Usuário lê próprio perfil" on public.perfis;
drop policy if exists "Cliente cria próprio perfil" on public.perfis;
drop policy if exists "Cliente atualiza próprio perfil" on public.perfis;
drop policy if exists "Dono lê clientes" on public.perfis;

create policy "Usuário lê próprio perfil"
on public.perfis for select to authenticated
using ((select auth.uid()) = id);

create policy "Cliente cria próprio perfil"
on public.perfis for insert to authenticated
with check ((select auth.uid()) = id and role='cliente');

create policy "Cliente atualiza próprio perfil"
on public.perfis for update to authenticated
using ((select auth.uid()) = id and role='cliente')
with check ((select auth.uid()) = id and role='cliente');

create policy "Dono lê clientes"
on public.perfis for select to authenticated
using (
  (select auth.uid()) = id
  or exists (select 1 from public.perfis dono where dono.id=(select auth.uid()) and dono.role='dono')
);

drop policy if exists "Qualquer pessoa cria pedido" on public.pedidos;
drop policy if exists "Cliente lê próprios pedidos" on public.pedidos;
drop policy if exists "Dono atualiza pedidos" on public.pedidos;

create policy "Qualquer pessoa cria pedido"
on public.pedidos for insert to anon,authenticated with check (true);

create policy "Cliente lê próprios pedidos"
on public.pedidos for select to authenticated
using (
  cliente_id=(select auth.uid())
  or exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono')
);

create policy "Dono atualiza pedidos"
on public.pedidos for update to authenticated
using (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'))
with check (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'));

-- 5. Bucket de imagens
insert into storage.buckets (id,name,public)
values ('produtos','produtos',true)
on conflict (id) do update set public=true;

drop policy if exists "Fotos públicas" on storage.objects;
drop policy if exists "Dono envia fotos" on storage.objects;
drop policy if exists "Dono remove fotos" on storage.objects;

create policy "Fotos públicas"
on storage.objects for select to public
using (bucket_id='produtos');

create policy "Dono envia fotos"
on storage.objects for insert to authenticated
with check (
  bucket_id='produtos'
  and exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono')
);

create policy "Dono remove fotos"
on storage.objects for delete to authenticated
using (
  bucket_id='produtos'
  and exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono')
);

-- O cliente pode fazer pedido sem criar conta.
-- A conta é opcional para histórico e promoções.
