-- PEDIDOFLOW V2 - EXECUTE NO SQL EDITOR

create table if not exists public.perfis (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text default '',
  role text not null default 'cliente' check (role in ('cliente','dono')),
  whatsapp text default '',
  aceita_promocoes boolean not null default false,
  consentimento_em timestamptz,
  criado_em timestamptz default now()
);

alter table public.perfis enable row level security;

drop policy if exists "Usuário lê próprio perfil" on public.perfis;
drop policy if exists "Cliente cria próprio perfil" on public.perfis;
drop policy if exists "Cliente atualiza próprio perfil" on public.perfis;
drop policy if exists "Dono lê clientes" on public.perfis;

create policy "Usuário lê próprio perfil"
on public.perfis for select to authenticated
using ((select auth.uid()) = id);

create policy "Cliente cria próprio perfil"
on public.perfis for insert to authenticated
with check ((select auth.uid()) = id and role = 'cliente');

create policy "Cliente atualiza próprio perfil"
on public.perfis for update to authenticated
using ((select auth.uid()) = id and role = 'cliente')
with check ((select auth.uid()) = id and role = 'cliente');

create policy "Dono lê clientes"
on public.perfis for select to authenticated
using (
  (select auth.uid()) = id
  or exists (
    select 1 from public.perfis dono
    where dono.id = (select auth.uid()) and dono.role = 'dono'
  )
);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  numero integer not null,
  cliente_id uuid references auth.users(id) on delete set null,
  cliente_nome text not null,
  cliente_telefone text default '',
  tipo_entrega text default 'Entrega',
  endereco text default '',
  bairro text default '',
  referencia text default '',
  pagamento text default '',
  observacoes text default '',
  subtotal numeric(10,2) not null default 0,
  taxa_entrega numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  status text not null default 'Recebido',
  itens jsonb not null default '[]'::jsonb,
  criado_em timestamptz default now()
);

alter table public.pedidos enable row level security;

drop policy if exists "Qualquer pessoa cria pedido" on public.pedidos;
drop policy if exists "Cliente lê próprios pedidos" on public.pedidos;
drop policy if exists "Dono atualiza pedidos" on public.pedidos;

create policy "Qualquer pessoa cria pedido"
on public.pedidos for insert to anon,authenticated with check (true);

create policy "Cliente lê próprios pedidos"
on public.pedidos for select to authenticated
using (
  cliente_id = (select auth.uid())
  or exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono')
);

create policy "Dono atualiza pedidos"
on public.pedidos for update to authenticated
using (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'))
with check (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'));

-- Produtos e configurações: leitura pública e escrita apenas pelo dono
alter table public.produtos enable row level security;
alter table public.configuracoes enable row level security;

drop policy if exists "Produtos visíveis publicamente" on public.produtos;
drop policy if exists "Dono cadastra produtos" on public.produtos;
drop policy if exists "Dono edita produtos" on public.produtos;
drop policy if exists "Dono exclui produtos" on public.produtos;

create policy "Produtos visíveis publicamente" on public.produtos for select to anon,authenticated using (true);
create policy "Dono cadastra produtos" on public.produtos for insert to authenticated
with check (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'));
create policy "Dono edita produtos" on public.produtos for update to authenticated
using (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'))
with check (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'));
create policy "Dono exclui produtos" on public.produtos for delete to authenticated
using (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'));

drop policy if exists "Configurações visíveis publicamente" on public.configuracoes;
drop policy if exists "Dono cadastra configurações" on public.configuracoes;
drop policy if exists "Dono edita configurações" on public.configuracoes;

create policy "Configurações visíveis publicamente" on public.configuracoes for select to anon,authenticated using (true);
create policy "Dono cadastra configurações" on public.configuracoes for insert to authenticated
with check (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'));
create policy "Dono edita configurações" on public.configuracoes for update to authenticated
using (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'))
with check (exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono'));

-- Bucket público de fotos
insert into storage.buckets (id,name,public)
values ('produtos','produtos',true)
on conflict (id) do update set public=true;

drop policy if exists "Fotos públicas" on storage.objects;
drop policy if exists "Dono envia fotos" on storage.objects;
drop policy if exists "Dono remove fotos" on storage.objects;

create policy "Fotos públicas" on storage.objects for select to public using (bucket_id='produtos');
create policy "Dono envia fotos" on storage.objects for insert to authenticated
with check (
  bucket_id='produtos'
  and exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono')
);
create policy "Dono remove fotos" on storage.objects for delete to authenticated
using (
  bucket_id='produtos'
  and exists (select 1 from public.perfis p where p.id=(select auth.uid()) and p.role='dono')
);

-- IMPORTANTE:
-- Authentication > Providers > Email:
-- mantenha Email ativado e desative Confirm email.
